### ISSUE TITLE
Reduce travis apt list

### ISSUE THREAD

**Issue by mpadge** [ATFutures/geoplumber#38]
Following [this short discussion](https://github.com/ATFutures/geoplumber/commit/8ea0fbfefcf4c7380db86642aedf41d30a7cc92f)

**Comment by layik** [comment]
[This](url
https://github.com/ATFutures/geoplumber/commit/81c6bf007db421acd017cf8ac9704886990f2052) has decreased the [build time](https://travis-ci.org/ATFutures/geoplumber/builds) on travis (from about 6 to 11 mins to about 3 mins) and also allows us to write more tests.

**Comment by layik** [comment]
Looks like this will get much better if we can do similar to what we have don't for [ATT](https://github.com/ATFutures/activeTransportToolbox/blob/master/Dockerfile).

**Comment by layik** [comment]
```
# skip vignette on travis.
# thanks to https://stackoverflow.com/a/41945450/2332101
r_check_args: "--no-vignettes"```
No point of taking ages on travis to rebuild exactly the same thing.

**Comment by layik** [comment]
```
addons:
  apt:
    packages:
      - libudunits2-dev # paper.Rmd see travis builds/508333361#L1622
      - libgdal-dev
      - libgeos-dev
      - libssl-dev
      - xclip

````
This did not work as I expected.
https://stackoverflow.com/a/41945450/2332101
